### ISSUE TITLE
Create a gentle introduction to resilience engineering for devops practioners

### ISSUE THREAD

**Issue by snakescott** [lorin/resilience-engineering#10]
While this repo is a great resource and the papers here may indeed be "accessible to casual readers" (I am still in the "storming" phase and building / preparing to tackle a massive backlog), I hypothesize it is possible to onboard "devops practiioners" (for lack of a better term) faster and easier by targeting their context -- assuming familiarity with certain concepts, addressing common questions/confusion, etc. 

I may be able to help with the legwork here! This insight/issue also brought in collaboration with Ryan Kitchens, whose github handle I don't have at the moment or I would cc.

**Comment by lorin** [comment]
Ryan's handle is @thishitshome.

**Comment by snakescott** [comment]
... duh :-D

**Comment by lorin** [comment]
I'm with you that the community could really benefit from a resilience engineering introduction that is targeted specifically at people who build and operate software services.
