### ISSUE TITLE
Is it worth adding a link to: "Applying resilience thinking - Seven principles for building resilience in social-ecological systems"?

### ISSUE THREAD

**Issue by alexhollerith** [lorin/resilience-engineering#14]
I found this to be a very interesting set of principles https://applyingresilience.org/en/the-7-principles/ that seem to map/align nicely to/with  a lot of the material presented in this repository.
Started to create a PR but then couldn't find a good spot for the link and thought that maybe opening an issue would be the more sensible approach.

Thanks
A.

**Comment by lorin** [comment]
Gettin gna error hitting this site

**Comment by kmarekspartz** [comment]
Searching for the title, I found this alternate link: https://preparecenter.org/wp-content/sites/default/files/applying_resilience_seven_principles.pdf

**Comment by lorin** [comment]
Going to pass on this for now, because I don't recognize any of the authors from the resilience engineering community, so I assume that these are researchers from a different community (albeit one that still thinks about resilience!).
