### ISSUE TITLE
Woods' Resilience Engineering Short Course

### ISSUE THREAD

**Issue by chadothompson** [lorin/resilience-engineering#17]
I note that the link to Woods' Resilience Engineering short course is 404-ing.  Did it move, or has it been taken down?

The link in the introductory document: https://csel.engineering.osu.edu/ResilienceEngineering.html

**Comment by lorin** [comment]
That page is gone, but there are newer videos available on YouTube on https://www.youtube.com/playlist?list=PLvlZBj1NU_ikTy1ot30EbEbYMAoBf9eAt.

The original videos are actually still available, see https://github.com/lorin/res-eng-short-course-notes for links.

**Comment by lorin** [comment]
Fixed in f37f8c08207d51caf60d6d4211b111cff0fdea4d

**Comment by vonneudeck** [comment]
Hi Lorin, somehow the old broken link has sneaked back into the doc.

**Comment by lorin** [comment]
@vonneudeck These should all be fixed in da128f342b5e2a39170431345ac134af20c9c59c

**Comment by vonneudeck** [comment]
Awesome, thank you very much @lorin 🥰
